# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Github:
    url: https://github.com/redroy44/redroy44.github.io
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title:

# URL of the Home page image
index_cover: http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/img/home-bg.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-88448128-1

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/redroy44/
gitlab_url:
linkedin_url: https://pl.linkedin.com/in/piotr-bandurski
mailto: bandurski.piotr@gmail.com
